export type Lang = 'en' | 'es'

export type PresetId = 'breakfast' | 'run' | 'chicken'

const en = {
  sampleCaption: 'Sample data. Simulation of the Tracky UI built from the open source repo.',
  appLabel: 'Tracky',
  navLabel: 'Tracky',
  close: 'Close',
  send: 'Send',
  github: 'GitHub',
  logged: 'Entries logged successfully.',
  loggedFallback: 'I matched that to the closest sample I can log in this preview.',
  imageNote: 'This preview logs text prompts. Try one of the sample phrases.',
  themeNote: 'This preview stays on the dark theme.',
  squareHint: 'Select a square to see that day.',
  openDiary: 'Open diary',
  chatSuggestions: 'Sample prompts',
  todayFood: 'Food',
  todayExercise: 'Exercise',
  noFoodToday: 'No meals logged for today yet.',
  noExerciseToday: 'No exercises logged for today yet.',
  noCategory: 'No sessions in this sample category.',
  quantity: 'Quantity',
  presets: [
    { id: 'breakfast' as const, label: '2 eggs, toast and a coffee for breakfast' },
    { id: 'run' as const, label: 'Ran 30 minutes at a moderate pace' },
    { id: 'chicken' as const, label: '100 g of chicken breast for lunch' }
  ],
  beta: 'beta',
  version: 'Version 1.0.0',
  signIn: 'Sign In',
  switchLanguage: 'Switch language',
  toggleTheme: 'Toggle theme',
  light: 'Light',
  dark: 'Dark',
  system: 'System',
  languages: { en: 'English', es: 'Español' },
  units: { kcal: 'kcal', g: 'g', kg: 'kg', cm: 'cm', min: 'min', percent: '%' },
  nav: {
    overview: 'Overview',
    food: 'Food',
    exercise: 'Exercise',
    diary: 'Diary',
    settings: 'Settings'
  },
  meals: {
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    uncategorized: 'Uncategorized'
  },
  nutrition: {
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fats: 'Fats',
    consumed: 'Consumed:',
    remaining: 'Remaining:'
  },
  daysShort: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  chartDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  of: 'of',
  now: 'Now',
  sections: {
    nutrition: 'Nutrition',
    expenditure: 'Expenditure',
    scaleWeight: 'Scale Weight',
    goalProgress: 'Goal Progress',
    weightGoal: 'Weight {goal} Goal',
    nutritionTargets: 'Nutrition & Targets',
    consumed: 'Consumed',
    remaining: 'Remaining'
  },
  streaks: { food: 'Food Streak', exercise: 'Exercise Streak' },
  goalLose: 'lose',
  food: {
    title: 'Food',
    addMeal: 'Add Meal',
    registerFood: 'Register Food',
    aiChat: 'AI Chat',
    chatWithAI: 'Chat with AI',
    placeholder: 'Log 100 g of chicken breast for lunch',
    instruction: 'Please specify the food item, portion size, and meal group.',
    ofDailyGoal: 'of daily goal',
    tabs: {
      weekly: 'Weekly Trends',
      weight: 'Weight Changes',
      macro: 'Macronutrients',
      today: 'Goal (Today)',
      week: 'Goal (Week)'
    },
    weeklyTitle: 'Weekly Nutritional Trends',
    weightTitle: 'Weight Changes',
    macroTitle: 'Macronutrient Distribution',
    todayTitle: "Today's Goal Completion Percentage",
    weekTitle: 'Week Goal Completion Percentage'
  },
  dashboardChat: {
    title: 'Chat with AI',
    placeholder: 'Log 2 eggs for breakfast or 30 min run',
    instruction: 'Specify portions for food or duration and effort for exercises. Images are supported.'
  },
  exercise: {
    title: 'Exercise',
    addExercise: 'Add Exercise',
    chatWithAI: 'Chat with AI',
    placeholder: 'Log 30 minutes of cardio in the morning',
    instruction: 'Please specify the exercise, duration, intensity and diary group. You can also upload images from Apple Watch, treadmill displays, or fitness equipment.',
    categories: 'Categories',
    cards: {
      burned: 'Total Energy Burned',
      time: 'Total Exercise Time',
      avg: 'Avg. Session Duration',
      week: 'Exercises This Week',
      times: 'times'
    },
    energyTitle: 'Weekly Energy Burned',
    energyDesc: 'Calories burned for each day',
    reached: 'Reached {percent}% of weekly target',
    exceeded: 'Exceeded target by {percent}% this week',
    mostActive: '{time} is your most active time',
    duration: 'Duration',
    effort: 'Effort Level',
    energy: 'Energy Burned',
    efforts: { easy: 'Easy', moderate: 'Moderate', hard: 'Hard', 'very-hard': 'Very Hard' }
  },
  diary: {
    title: 'Diary',
    filters: 'Filters',
    entryTypes: 'Entry Types',
    date: 'Date',
    selectDate: 'Select Date',
    allDates: 'All Dates',
    diaryGroup: 'Diary Group',
    selectGroup: 'Select Diary Group',
    allGroups: 'All Diary Groups',
    daySummary: 'Day Summary',
    burned: 'Burned',
    cal: 'Cal',
    duration: 'Duration',
    types: { meal: 'meal', exercise: 'exercise', food: 'food', updates: 'updates' },
    kcal: 'kcal',
    kcalBurned: 'kcal burned',
    protein: 'protein',
    fat: 'fat',
    carbs: 'carbs',
    effort: 'Effort:',
    noFiltered: 'No entries found for the selected filters',
    noEntries: 'There are no entries to display yet',
    newFood: 'New Food Registration',
    newWeight: 'New Weight'
  },
  ai: {
    title: 'AI Chat',
    description: 'Describe meals or workouts and the AI will log them.',
    options: 'Chat options',
    clear: 'Clear history',
    storage: 'Storage usage:',
    analyzing: 'Analyzing...',
    entryPhoto: 'Entry photo',
    entryImage: 'Entry image',
    consumptionAdded: 'Consumption added successfully',
    exerciseAdded: 'Exercise added successfully'
  },
  settings: {
    title: 'Settings',
    subtitle: 'Configure the settings for this application',
    personal: 'Personal Information',
    goals: 'Preferences and Goals',
    born: 'Born',
    sex: 'Sex',
    activity: 'Activity Level',
    height: 'Height',
    weight: 'Weight',
    bodyFat: 'Body Fat Percentage (%)',
    goal: 'Fitness Goal',
    goalWeight: 'Goal Weight',
    sexValue: 'male',
    activityValue: 'Mostly Active',
    goalValue: 'lose'
  },
  categories: ['Gym', 'Cardio', 'Individual Sport', 'Team Sport', 'Outdoor Activity', 'Stretching & Mobility']
}

const es: typeof en = {
  sampleCaption: 'Datos de ejemplo. Simulación de la interfaz de Tracky construida a partir del repositorio de código abierto.',
  appLabel: 'Tracky',
  navLabel: 'Tracky',
  close: 'Cerrar',
  send: 'Enviar',
  github: 'GitHub',
  logged: 'Entradas registradas correctamente.',
  loggedFallback: 'Lo asocié con el ejemplo más cercano que puedo registrar en esta vista.',
  imageNote: 'Esta vista registra textos. Prueba una de las frases de ejemplo.',
  themeNote: 'Esta vista se queda en el tema oscuro.',
  squareHint: 'Selecciona un cuadro para ver ese día.',
  openDiary: 'Abrir diario',
  chatSuggestions: 'Frases de ejemplo',
  todayFood: 'Comida',
  todayExercise: 'Ejercicio',
  noFoodToday: 'Todavía no hay comidas registradas hoy.',
  noExerciseToday: 'Todavía no hay ejercicios registrados hoy.',
  noCategory: 'No hay sesiones en esta categoría de ejemplo.',
  quantity: 'Cantidad',
  presets: [
    { id: 'breakfast', label: '2 huevos, tostada y un café para el desayuno' },
    { id: 'run', label: 'Corrí 30 minutos a un ritmo moderado' },
    { id: 'chicken', label: '100 g de pechuga de pollo para el almuerzo' }
  ],
  beta: 'beta',
  version: 'Versión 1.0.0',
  signIn: 'Iniciar Sesión',
  switchLanguage: 'Cambiar idioma',
  toggleTheme: 'Cambiar tema',
  light: 'Claro',
  dark: 'Oscuro',
  system: 'Sistema',
  languages: { en: 'English', es: 'Español' },
  units: { kcal: 'kcal', g: 'g', kg: 'kg', cm: 'cm', min: 'min', percent: '%' },
  nav: {
    overview: 'Resumen',
    food: 'Comida',
    exercise: 'Ejercicio',
    diary: 'Diario',
    settings: 'Ajustes'
  },
  meals: {
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    dinner: 'Cena',
    snack: 'Merienda',
    uncategorized: 'Sin categoría'
  },
  nutrition: {
    calories: 'Calorías',
    protein: 'Proteína',
    carbs: 'Carbohidratos',
    fat: 'Grasa',
    fats: 'Grasas',
    consumed: 'Consumido:',
    remaining: 'Restante:'
  },
  daysShort: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
  days: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
  chartDays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
  of: 'de',
  now: 'Ahora',
  sections: {
    nutrition: 'Nutrición',
    expenditure: 'Gasto',
    scaleWeight: 'Peso en Báscula',
    goalProgress: 'Progreso del Objetivo',
    weightGoal: 'Objetivo de {goal} Peso',
    nutritionTargets: 'Nutrición y Objetivos',
    consumed: 'Consumido',
    remaining: 'Restante'
  },
  streaks: { food: 'Racha de Comida', exercise: 'Racha de Ejercicio' },
  goalLose: 'perder',
  food: {
    title: 'Comida',
    addMeal: 'Agregar Comida',
    registerFood: 'Registrar Comida',
    aiChat: 'Chat IA',
    chatWithAI: 'Chat con IA',
    placeholder: 'Registra 100 g de pechuga de pollo para el almuerzo',
    instruction: 'Por favor especifica el alimento, el tamaño de la porción y el grupo de comida.',
    ofDailyGoal: 'del objetivo diario',
    tabs: {
      weekly: 'Tendencias Semanales',
      weight: 'Cambios de Peso',
      macro: 'Macronutrientes',
      today: 'Objetivo (Hoy)',
      week: 'Objetivo (Semana)'
    },
    weeklyTitle: 'Tendencias Nutricionales Semanales',
    weightTitle: 'Cambios de Peso',
    macroTitle: 'Distribución de Macronutrientes',
    todayTitle: 'Porcentaje de Objetivo Completado Hoy',
    weekTitle: 'Porcentaje de Objetivo Completado Semanal'
  },
  dashboardChat: {
    title: 'Chat con IA',
    placeholder: 'Registra 2 huevos para el desayuno o 30 min de carrera',
    instruction: 'Especifica las porciones para comida o duración y esfuerzo para ejercicios. Se admiten imágenes.'
  },
  exercise: {
    title: 'Ejercicio',
    addExercise: 'Agregar Ejercicio',
    chatWithAI: 'Chat con IA',
    placeholder: 'Registra 30 minutos de cardio en la mañana',
    instruction: 'Por favor especifica el ejercicio, duración, intensidad y grupo del diario. También puedes subir imágenes de Apple Watch, pantallas de cinta o equipos de fitness.',
    categories: 'Categorías',
    cards: {
      burned: 'Energía Total Quemada',
      time: 'Tiempo Total de Ejercicio',
      avg: 'Duración Prom. de Sesión',
      week: 'Ejercicios Esta Semana',
      times: 'veces'
    },
    energyTitle: 'Energía Semanal Quemada',
    energyDesc: 'Calorías quemadas por día',
    reached: 'Alcanzaste {percent}% del objetivo semanal',
    exceeded: 'Superaste el objetivo por {percent}% esta semana',
    mostActive: '{time} es tu momento más activo',
    duration: 'Duración',
    effort: 'Nivel de Esfuerzo',
    energy: 'Energía Quemada',
    efforts: { easy: 'Fácil', moderate: 'Moderado', hard: 'Difícil', 'very-hard': 'Muy Difícil' }
  },
  diary: {
    title: 'Diario',
    filters: 'Filtros',
    entryTypes: 'Tipos de Entrada',
    date: 'Fecha',
    selectDate: 'Seleccionar Fecha',
    allDates: 'Todas las Fechas',
    diaryGroup: 'Grupo del Diario',
    selectGroup: 'Seleccionar Grupo del Diario',
    allGroups: 'Todos los Grupos del Diario',
    daySummary: 'Resumen del Día',
    burned: 'Quemadas',
    cal: 'Cal',
    duration: 'Duración',
    types: { meal: 'comida', exercise: 'ejercicio', food: 'alimento', updates: 'actualizaciones' },
    kcal: 'kcal',
    kcalBurned: 'kcal quemadas',
    protein: 'proteína',
    fat: 'grasa',
    carbs: 'carbohidratos',
    effort: 'Esfuerzo:',
    noFiltered: 'No se encontraron entradas para los filtros seleccionados',
    noEntries: 'Aún no hay entradas para mostrar',
    newFood: 'Nuevo Registro de Alimento',
    newWeight: 'Nuevo Peso'
  },
  ai: {
    title: 'Chat IA',
    description: 'Describe comidas o entrenamientos y la IA los registrará.',
    options: 'Opciones del chat',
    clear: 'Borrar historial',
    storage: 'Uso de almacenamiento:',
    analyzing: 'Analizando...',
    entryPhoto: 'Foto de entrada',
    entryImage: 'Imagen de entrada',
    consumptionAdded: 'Consumo agregado exitosamente',
    exerciseAdded: 'Ejercicio agregado exitosamente'
  },
  settings: {
    title: 'Ajustes',
    subtitle: 'Configura los ajustes de esta aplicación',
    personal: 'Información Personal',
    goals: 'Preferencias y Objetivos',
    born: 'Nacimiento',
    sex: 'Sexo',
    activity: 'Nivel de Actividad',
    height: 'Altura',
    weight: 'Peso',
    bodyFat: 'Porcentaje de Grasa Corporal (%)',
    goal: 'Objetivo Fitness',
    goalWeight: 'Peso Objetivo',
    sexValue: 'masculino',
    activityValue: 'Mayormente Activo',
    goalValue: 'perder'
  },
  categories: ['Gimnasio', 'Cardio', 'Deporte individual', 'Deporte de equipo', 'Actividad al aire libre', 'Estiramiento y movilidad']
}

export const copy: Record<Lang, typeof en> = { en, es }

export function promptsFor (id: PresetId): string[] {
  return [en.presets.find((item) => item.id === id)?.label, es.presets.find((item) => item.id === id)?.label].filter((item): item is string => Boolean(item))
}
